contact_links:
  - name: ❓ Support question
    url: https://github.com/Cap-go/capacitor-plugins/discussions
    about: This issue tracker is not for support questions. Please post your question on GitHub Discussions.
